---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: periodic-slack
spec:
  concurrencyPolicy: Forbid
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: chaos-period-slack
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: chaos-periodic-slack
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: chaostoolkit
          restartPolicy: Never
          containers:
          - name: chaostoolkit
            image: vfarcic/chaostoolkit:1.4.1-2
            args:
            - --verbose
            - run
            - --journal-path
            - /results/journal-health-http.json
            - /experiment/health-http.yaml
            env:
            - name: CHAOSTOOLKIT_IN_POD
              value: "true"
            - name: INGRESS_HOST
              value: 20.75.157.19
            volumeMounts:
            - name: experiments
              mountPath: /experiment
              readOnly: true
            - name: settings
              mountPath: /root/.chaostoolkit
              readOnly: true
            - name: results
              mountPath: /results
              readOnly: false
            resources:
              limits:
                cpu: 20m
                memory: 64Mi
              requests:
                cpu: 20m
                memory: 64Mi
          volumes:
          - name: experiments
            configMap:
              name: chaostoolkit-experiments
          - name: settings
            configMap:
              name: chaostoolkit-settings
          - name: results
            persistentVolumeClaim:
              claimName: go-demo-8-chaos

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: go-demo-8-chaos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
