---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaostoolkit
  namespace: webapp
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaostoolkit
  namespace: webapp
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  - "batch"
  resources:
  - pods
  - deployments
  - jobs
  verbs:
  - list
  - get
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  verbs:
  - list
  - get
  - create
  - delete
  - update
  - patch
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaostoolkit
  namespace: webapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaostoolkit
subjects:
  - kind: ServiceAccount
    name: chaostoolkit
