apiVersion: v1
kind: ConfigMap
metadata:
  name: chaostoolkit-settings
data:
  settings.yaml: |
    notifications:
    - type: plugin
      module: chaosslack.notification
      token: <token>
      channel: general
      events:
      - discover-failed
      - run-failed
      - validate-failed
